name: First-Script

on: [push]

jobs:
  syntax:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update && sudo apt install -y php && php --version
      - run: find src -type f -name "*.php" | xargs -n1 php -l
